language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t tharindu1996/docker-containers -f Dockerfile.dev .

script:
    -  docker run -e CI=true tharindu1996/docker-containers npm run test

deploy: 
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-containers"
    env: "DockerContainers-env"
    bucket_name: "elasticbeanstalk-ap-south-1-694743093041"
    bucket_path: "docker-containers"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: "$AWS_SECRET_KEY"
    
         