language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t tharindu1996/docker-containers -f Dockerfile.dev .

script:
    -  docker run -e CI=true tharindu1996/docker-containers npm run test


